spring:
  profiles:
    active: dev
  application:
    name: data-analysis
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/analysis?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # idleTimeout是允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 30000
      # 连接池大小
      maximum-pool-size: 20
      # minimumIdle是HikariCP在连接池中维护的最小空闲连接数。
      minimum-idle: 5
      max-lifetime: 1200000
      connection-timeout: 20000
    schema: classpath:schema/govern-init.sql
    data: classpath:data/govern-data.sql
    initialization-mode: always
    sql-script-encoding: utf-8
    continue-on-error: true
server:
  port: 0
logging:
  config: classpath:log4j.xml
  level:
    root: warn
spark:
  master: local[*]
  batch-size: 1000
  num-executors:
  #  实时流处理间隔耗时
  duration: 1